apiVersion: v1
kind: Service
metadata:
    name: "myakscluster"
    labels:
        app: "myakscluster"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "myakscluster"